import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";
import ThemeLocal from "@/components/ui/ThemeLocal";
import NextTopLoader from "nextjs-toploader";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        id="main-div"
        className={cn(
          "min-h-screen overflow-hidden bg-background antialiased",
          fontSans.className
        )}
      >
        <NextUIProvider>
          <SessionProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <NextTopLoader
                color="linear-gradient(to right, #fc466b, #3f5efb)"
                initialPosition={0.08}
                crawlSpeed={500}
                height={5}
                crawl={true}
                showSpinner={false}
                easing="ease"
                speed={500}
              />
              <main
                className={cn(
                  "relative h-[100dvh] overflow-auto scrollbar-none scrollbar-track-gray-100  scrollbar-thumb-gray-300 dark:scrollbar-track-gray-900 dark:scrollbar-thumb-gray-800 sm:scrollbar-thin "
                )}
              >
                <div className="flex-1">{children}</div>
              </main>
              <ThemeLocal />
            </ThemeProvider>
          </SessionProvider>
        </NextUIProvider>
        <Toaster />
      </body>
    </html>
  );
}
